### ISSUE TITLE
Fluent waits are not working when the property createAnimatedGif=false

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#255]
**Describe the bug**
Fluent waits are not working when the property createAnimatedGif=false causing the test to fail unexpectedly.

**To Reproduce**
1. From the VisualValidations.property file, createAnimatedGif=false
2. Try to execute a scenario that require the fluent waits

**Expected behavior**
The fluent waits should be working normally when the property createAnimatedGif=false

**Sample Exception**
```
java.lang.AssertionError: Element Action [identifyUniqueElement] failed. With the following test data [zero elements found matching this locator "By.xpath: //div[@e2e-test='feedback-message']//h1".].
	at org.testng.Assert.fail(Assert.java:99)
	at com.shaft.gui.element.ElementActions.failAction(ElementActions.java:1525)
	at com.shaft.gui.element.ElementActions.failAction(ElementActions.java:1351)
	at com.shaft.gui.element.ElementActions.identifyUniqueElement(ElementActions.java:1586)
	at com.shaft.gui.element.ElementActions.identifyUniqueElement(ElementActions.java:1360)
	at com.shaft.gui.element.ElementActions.getText(ElementActions.java:673)
```

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context**
N/A

**Comment by MohabMohie** [comment]
Closed, pending PR merge.
