### ISSUE TITLE
closureActivities fails while attaching the Extent emailable report and the Allure report is not opened automatically in some cases

### ISSUE THREAD

**Issue by MahmoudElSharkawy** [MohabMohie/SHAFT_ENGINE#256]
**Describe the bug**
closureActivities fails while attaching the Extent emailable report in some cases and the Allure report is not opened automatically. 

**To Reproduce**
N/A

**Expected behavior**
* closureActivities should al pass 
* Allure Report should open automatically
* The Extent emailable report should be generated in all cases

**Screenshots**
![image](https://user-images.githubusercontent.com/46620378/107953318-a562cc80-6fa3-11eb-8715-0431aa97640f.png)

**Sample Exception**
```
java.lang.AssertionError: File Action [readFromFile] failed.
	at org.testng.Assert.fail(Assert.java:87)
	at com.shaft.cli.FileActions.failAction(FileActions.java:583)
	at com.shaft.cli.FileActions.failAction(FileActions.java:577)
	at com.shaft.cli.FileActions.readFromFile(FileActions.java:307)
	at com.shaft.tools.io.LogsReporter.attachExtentReport(LogsReporter.java:47)
	at com.shaft.tools.io.LogsReporter.closureActivities(LogsReporter.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:351)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3399)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3436)
	at com.shaft.cli.FileActions.readFromFile(FileActions.java:303)
	... 21 more
```

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
The the issues is random, and needs more investigation

**Comment by MohabMohie** [comment]
Closed, pending PR merge.

**Comment by MahmoudElSharkawy** [comment]
After further testing, the issues is related to the  ReportManager.attach() method is it fails with some cases.

**Steps to reproduce:** 
Try to attach the html file attached below using the ReportManager.attach() method in the allure report.
[ExtentReports_16-02-2021_23-36-27-0576-pm.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/5992301/ExtentReports_16-02-2021_23-36-27-0576-pm.zip)

**Actual:**
Getting **MalformedInputException** and the test fails.
![image](https://user-images.githubusercontent.com/46620378/108136403-ac343100-70c2-11eb-9ae7-11c2ed1c5d80.png)


**Sample Exception:**
```
java.nio.charset.MalformedInputException:
Input length = 1
java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
java.base/java.nio.file.Files.readAllLines(Files.java:3399)
java.base/java.nio.file.Files.readAllLines(Files.java:3436)
com.shaft.cli.FileActions.readFromFile(FileActions.java:303)
testPackage01.Test.test(Test.java:18)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:564)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
org.testng.TestRunner.privateRun(TestRunner.java:764)
org.testng.TestRunner.run(TestRunner.java:585)
org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
org.testng.SuiteRunner.run(SuiteRunner.java:286)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
org.testng.TestNG.runSuites(TestNG.java:1069)
org.testng.TestNG.run(TestNG.java:1037)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```
