### ISSUE TITLE
"w3c chrome options" is blocking SHAFT to be executed on chrome browser 

### ISSUE THREAD

**Issue by HaithamGitHub** [MohabMohie/SHAFT_ENGINE#334]
Using the latest version of Chrome V91 and SHAFT, The  browser will be launched successfully but not able to access any controls on the browser (example:  type using ElmenetActions.Type not working) 
Error: 
**_Cannot invoke "String.trim()" because the return value of "org.openqa.selenium.WebElement.getAttribute(String)" is null_**

**_investigation :_** 
the reason of this error adding chrome option chOptions.setExperimentalOption("w3c", false);  to the default (see the below screenshot last line)

**_a possible solution to fix this issue_** is to remove this W3C option from the default values

![image](https://user-images.githubusercontent.com/44056150/120934284-069edf00-c6fe-11eb-8beb-d0b688619779.png)

**Comment by MohabMohie** [comment]
This is actually an unrelated issue and I already have a PR open to fix it.

It's blocking the type method, and the stacktrace shows that it's happening in the clear before type method.

Would you share the stacktrace please?

In the meantime, you can use typeAppend instead of type and it will work without throwing the exception.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: HaithamGitHub ***@***.***>
Sent: Sunday, June 6, 2021 7:49:10 PM
To: MohabMohie/SHAFT_ENGINE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MohabMohie/SHAFT_ENGINE] "w3c chrome options" is blocking SHAFT to be executed on chrome browser (#334)


Using the latest version of Chrome V91 and SHAFT, The browser will be launched successfully but not able to access any controls on the browser (example: type using ElmenetActions.Type not working)
Error:
Cannot invoke "String.trim()" because the return value of "org.openqa.selenium.WebElement.getAttribute(String)" is null

investigation :
the reason of this error adding chrome option chOptions.setExperimentalOption("w3c", false); to the default (see the below screenshot last line)

a possible solution to fix this issue is to remove this W3C option from the default values

[image]<https://user-images.githubusercontent.com/44056150/120934284-069edf00-c6fe-11eb-8beb-d0b688619779.png>

**Comment by HaithamGitHub** [comment]
[RemoteTestNG] detected TestNG version 7.4.0

################################################################################################################################################
Detected SHAFT Engine Version: [5.3.20210519]
################################################################################################################################################

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.cdx.testcases.ImportFilesTests.BeforeSuite]
################################################################################################################################################
BeforeSuite

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.cdx.testcases.ImportFilesTests.BeforeTest]
################################################################################################################################################
BeforeTest

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.cdx.testcases.ImportFilesTests.BeforeClass]
################################################################################################################################################
BeforeClass

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.cdx.testcases.ImportFilesTests.BeforeMethod]
################################################################################################################################################
BeforeMethod
[ReportManager] Successfully created attachment [File Action Actual Result - Command Log] @07-06-2021 10:52:17.0893 AM
Starting ChromeDriver 91.0.4472.19 (1bf021f248676a0b2ab3ee0561d83a59e424c23e-refs/branch-heads/4472@{#288}) on port 33291
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1623055945.983][WARNING]: Ignoring unrecognized log type: client
[1623055945.983][WARNING]: Ignoring unrecognized log type: profiler
[1623055945.983][WARNING]: Ignoring unrecognized log type: server
Jun 07, 2021 10:52:28 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: BeforeMethod] @07-06-2021 10:52:33.0942 AM

################################################################################################################################################
Starting Execution:	[1 out of 1] test cases in the current suite
Test Method:		[com.cdx.testcases.ImportFilesTests.ImportFileIPC1754]
################################################################################################

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.cdx.testcases.ImportFilesTests.AfterMethod]
################################################################################################################################################
[ReportManager] AfterMethod @07-06-2021 10:52:35.0207 AM
[ReportManager] Test Case:[ImportFileIPC1754] is Failed, Reason of the Failure : [java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "org.openqa.selenium.WebElement.getAttribute(String)" is null] @07-06-2021 10:52:35.0208 AM
[ReportManager] Closing All Browser ... @07-06-2021 10:52:55.0224 AM
[ReportManager] Successfully created attachment [Selenium WebDriver Logs - performance] @07-06-2021 10:52:55.0382 AM
[ReportManager] Successfully created attachment [Selenium WebDriver Logs - browser] @07-06-2021 10:52:55.0392 AM
[ReportManager] Successfully created attachment [Selenium WebDriver Logs - driver] @07-06-2021 10:52:55.0590 AM

**Comment by MohabMohie** [comment]
Thanks for sharing the execution log. Kindly share the exception stacktrace to be able to better trace the problem.

**Comment by HaithamGitHub** [comment]
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "org.openqa.selenium.WebElement.getAttribute(String)" is null
	at com.shaft.gui.element.WebDriverElementActions.determineSuccessfulTextLocationStrategy(WebDriverElementActions.java:1455)
	at com.shaft.gui.element.WebDriverElementActions.typeWrapper(WebDriverElementActions.java:1752)
	at com.shaft.gui.element.WebDriverElementActions.type(WebDriverElementActions.java:1172)
	at com.shaft.gui.element.ElementActions.type(ElementActions.java:555)
	at com.cdx.pages.LoginPage.ValidLogin(LoginPage.java:95)
	at com.cdx.testcases.SDoCTests.CreateSDoC_GUIDependencies(SDoCTests.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by MohabMohie** [comment]
Fixed, merged, and released.

**Comment by HaithamGitHub** [comment]
Thanks, Mohab for the release and the updates. I have checked the new version but still failed in many methods ( examples type, select) 


**chOptions.setExperimentalOption("w3c", false);
hint: both the below issues will be fixed in case you have the chrome options -> true**

### - Exmaple1 (ElementActions.Type()):

_I have the below field:_
td valign="top" nowrap="" class="xvb" theme="medium"><input id="pt1:itUserId::content" name="pt1:itUserId" style="width:auto" class="x25" theme="medium" size="15" maxlength="50" type="text" title="gcdal002"

need to add include **title** with (text, content, value) in the below function as the return null : 

_private static TextDetectionStrategy determineSuccessfulTextLocationStrategy(WebDriver driver, By elementLocator) {
	if (DriverFactoryHelper.isMobileNativeExecution()) {
		return TextDetectionStrategy.TEXT;
	}
	String text = driver.findElement(elementLocator).getText();
	String content = driver.findElement(elementLocator).getAttribute(TextDetectionStrategy.CONTENT.getValue());
	String value = driver.findElement(elementLocator).getAttribute(TextDetectionStrategy.VALUE.getValue());

	TextDetectionStrategy successfulTextLocationStrategy;
	if (text != null && !"".equals(text.trim())) {
		successfulTextLocationStrategy = TextDetectionStrategy.TEXT;
	} else if (content != null && !"".equals(content.trim())) {
		successfulTextLocationStrategy = TextDetectionStrategy.CONTENT;
	} else if (value != null && !"".equals(value.trim())) {
		successfulTextLocationStrategy = TextDetectionStrategy.VALUE;
	} else {
		successfulTextLocationStrategy = TextDetectionStrategy.UNDEFINED;
	}
	return successfulTextLocationStrategy;
}_

////////////////////////////////////////////////////
trace:
java.lang.AssertionError: Element Action [type] failed.
	at org.testng.Assert.fail(Assert.java:99)
	at com.shaft.gui.element.WebDriverElementActions.failAction(WebDriverElementActions.java:1457)
	at com.shaft.gui.element.WebDriverElementActions.failAction(WebDriverElementActions.java:1306)
	at com.shaft.gui.element.WebDriverElementActions.type(WebDriverElementActions.java:1166)
	at com.shaft.gui.element.ElementActions.type(ElementActions.java:554)
	at com.cdx.pages.LoginPage.ValidLogin(LoginPage.java:95)
	at com.cdx.testcases.UserTests.CheckEnv(UserTests.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
////////////////////////////////////////////////////////////////////////////////

### Example2: Select options fail

org.openqa.selenium.NoSuchElementException: Cannot locate option with index: 1
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EG-CND60820RG', ip: '10.218.164.128', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.setSelectedByIndex(Select.java:297)
	at org.openqa.selenium.support.ui.Select.selectByIndex(Select.java:172)
	at com.shaft.gui.element.WebDriverElementActions.select(WebDriverElementActions.java:973)
	at com.shaft.gui.element.ElementActions.select(ElementActions.java:459)
	at com.cdx.pages.LoginPage.ValidLogin(LoginPage.java:104)
	at com.cdx.testcases.UserTests.CheckEnv(UserTests.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by MohabMohie** [comment]
Hello Haitham,

1. For the type case, kindly provide any link or reference stating that the text typed in an element should exist as the value of the title attribute. I will bw happy to add that case then. In the meantime, kindly use the configuration manager to disable force check that text is typed correctly.
2. For the select case, kindly post to the support group showing your code, the element locator used, and the page dom.
3. Kindly share your evidence that any of this is related to w3c compliance.

**Comment by HaithamGitHub** [comment]
issue Fixed! Thanks

**Comment by MohabMohie** [comment]
Great news! Thank you for confirming 🙏
