### ISSUE TITLE
[Test Closure Activities] when "generateExtentReports=true" null pointer exception happened at extent report 

### ISSUE THREAD

**Issue by magdyheiba** [MohabMohie/SHAFT_ENGINE#357]
**Describe the bug**
when "generateExtentReports=true" null pointer exception happened at extent report 
**To Reproduce**
1. create a simple cucumber project
2. make generateExtentReports=true 
3. run project from CMD using testng runner

**Expected behavior**
Test should be run and report generated successfully

**Screenshots**

Null pointer exception happened 
`Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "com.shaft.tools.io.ReportManagerHelper.extentTest" is null
java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because "com.shaft.tools.io.ReportManagerHelper.extentTest" is null
	at com.shaft.tools.io.ReportManagerHelper.extentReportsFail(ReportManagerHelper.java:437)
	at com.shaft.tools.listeners.InvokedMethodListener.updateIssuesLog(InvokedMethodListener.java:150)
	at com.shaft.tools.listeners.InvokedMethodListener.afterInvocation(InvokedMethodListener.java:123)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:60)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:56)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:636)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)`
**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Comment by MohabMohie** [comment]
this issue will be closed after the PR is merged and release is created. feel free to reopen it if it's not fixed completely.
